# Generated by Django 2.0.5 on 2018-08-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('useremail', models.TextField()),
                ('userbirth', models.DateField()),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
