# Generated by Django 2.0.5 on 2018-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantname', models.TextField()),
                ('bookname', models.TextField()),
                ('bookperson', models.PositiveIntegerField()),
                ('booktel', models.TextField()),
                ('bookdate', models.TextField()),
                ('bookwhen', models.DateField()),
                ('booktime', models.DateField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.TextField()),
                ('rtype', models.TextField()),
                ('rtel', models.TextField()),
                ('raddress', models.DateField()),
                ('rweb', models.TextField()),
                ('rintroduction', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
